{"asctime": "2021-09-27 17:19:46,846", "filename": "code_logzero_2.py", "funcName": "<module>", "levelname": "INFO", "levelno": 20, "lineno": 8, "module": "code_logzero_2", "message": "This log message saved in the log file", "name": "My Custom Logger", "pathname": "c:/Users/f.delgadomartinez/Desktop/INVENTOS PYTHON/logzero/code_logzero_2.py", "process": 12708, "processName": "MainProcess", "threadName": "MainThread"}
{"asctime": "2021-09-27 17:19:46,856", "filename": "code_logzero_2.py", "funcName": "<module>", "levelname": "WARNING", "levelno": 30, "lineno": 9, "module": "code_logzero_2", "message": "This log message saved in the log file", "name": "My Custom Logger", "pathname": "c:/Users/f.delgadomartinez/Desktop/INVENTOS PYTHON/logzero/code_logzero_2.py", "process": 12708, "processName": "MainProcess", "threadName": "MainThread"}
{"asctime": "2021-09-27 17:19:46,858", "filename": "modulo_interno.py", "funcName": "funcion_en_modulo_interno", "levelname": "CRITICAL", "levelno": 50, "lineno": 10, "module": "modulo_interno", "message": "error en modulo interno", "name": "My Custom Logger", "pathname": "c:\\Users\\f.delgadomartinez\\Desktop\\INVENTOS PYTHON\\logzero\\modulo_interno.py", "process": 12708, "processName": "MainProcess", "threadName": "MainThread"}
